var dataUser =[
    {
        "id": 1,
        "fullName":"Duc Hao 1",
        "email":"duchao1@gmail.com",
        "phoneNumber": "07000001",
        "role":2,
        "isAvailable": true,
    },
    {
        "id": 2,
        "fullName":"Duc Hao 2",
        "email":"duchao2@gmail.com",
        "phoneNumber": "07000002",
        "role":0,
        "isAvailable": true,
    },
    {
        "id": 3,
        "fullName":"Duc Hao 3",
        "email":"duchao3@gmail.com",
        "phoneNumber": "07000003",
        "role":3,
        "isAvailable": true,
    },
    {
        "id": 4,
        "fullName":"Duc Hao 4",
        "email":"duchao4@gmail.com",
        "phoneNumber": "07000004",
        "role":0,
        "isAvailable": false,
    },
    {
        "id": 5,
        "fullName":"Duc Hao 5",
        "email":"duchao5@gmail.com",
        "phoneNumber": "07000005",
        "role":0,
        "isAvailable": false,
    },
    {
        "id": 6,
        "fullName":"Duc Hao 6",
        "email":"duchao6@gmail.com",
        "phoneNumber": "07000006",
        "role":0,
        "isAvailable": true,
    },
    {
        "id": 7,
        "fullName":"Duc Hao 7",
        "email":"duchao7@gmail.com",
        "phoneNumber": "07000006",
        "role":0,
        "isAvailable": true,
    },
    {
        "id": 8,
        "fullName":"Duc Hao 8",
        "email":"duchao8@gmail.com",
        "phoneNumber": "07000008",
        "role":0,
        "isAvailable": true,
    },
    {
        "id": 9,
        "fullName":"Duc Hao 9",
        "email":"duchao8@gmail.com",
        "phoneNumber": "07000008",
        "role":0,
        "isAvailable": true,
    },
    {
        "id": 10,
        "fullName":"Duc Hao 10",
        "email":"duchao8@gmail.com",
        "phoneNumber": "07000008",
        "role":0,
        "isAvailable": true,
    },
    {
        "id": 11,
        "fullName":"Duc Hao 11",
        "email":"duchao8@gmail.com",
        "phoneNumber": "07000008",
        "role":0,
        "isAvailable": true,
    },
    {
        "id": 12,
        "fullName":"Duc Hao 12",
        "email":"duchao8@gmail.com",
        "phoneNumber": "07000008",
        "role":0,
        "isAvailable": true,
    },
];
export default dataUser;